#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu May 27 10:47:22 PDT 2021
# SW Build 2902540 on Wed May 27 19:54:35 MDT 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim dsp_tester_behav -key {Behavioral:sim_2:Functional:dsp_tester} -tclbatch dsp_tester.tcl -view /home/donovan/deon_fpga/dsp_tester_behav.wcfg -log simulate.log"
xsim dsp_tester_behav -key {Behavioral:sim_2:Functional:dsp_tester} -tclbatch dsp_tester.tcl -view /home/donovan/deon_fpga/dsp_tester_behav.wcfg -log simulate.log

